language: cpp
compiler:
  - clang
  - gcc
env:
 - BUILD_CMAKE=no
 - BUILD_CMAKE=yes
before_install:
  - $CC --version
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
    #libstdc++-4.8 is needed by Clang to build
  - sudo apt-get -qq install  libstdc++-4.8-dev
  - sudo apt-get build-dep wireshark
  - sudo apt-get install cmake libgtk-3-0 libglib2.0-0 libgdk-pixbuf2.0-0 libcairo2 libqt4-dev
  - $CC --version
before_script:
  if [ ${BUILD_CMAKE} == "yes" ]; then mkdir build && cd build && cmake ..; else ./autogen.sh && ./configure --with-gtk2; fi
script:
  - make
